### Esta es una API REST de películas y podemos probar los endpoint en este archivo .http gracias a la extensión de VSCode REST Client.
### Para esto creamos un archivo .http y escribimos los endpoint que se encuentran que queremos probar.

### Recuperar todas las tareas
GET http://localhost:4000/api/v1/tasks

### Recuperar una tarea por ID
GET http://localhost:4000/api/v1/tasks/0x1a504f9494

### Crear una nueva tarea
POST http://localhost:4000/api/v1/tasks
Content-Type: application/json

{
    "label": "Tarea 3",
    "scheduledAt": "2023-11-28T20:19:56.746Z"
}


### Actualizar una tarea
PATCH http://localhost:4000/api/v1/tasks/0x1a504f94c6
Content-Type: application/json

{
  "status": "CANCELLED"
}

### Borrar una tarea
DELETE http://localhost:4000/api/v1/tasks/0x1a504f8e3d























